### ISSUE TITLE
Url/Links

### ISSUE THREAD

**Issue by profesionalleet1337** [security-softwares/anonymous-sms#2]
The tool is work fine, but its impossible to put url, link in him. Like many of the others gits, this doesn't allow to do its. Could be upgraded , fix somehow ? The main purpose of this type of tools, it to could be put links. Please , improve mate ! I Will be really grateful if you could done this for most people.
Happy Holidays and wish all the best !

**Comment by security-softwares** [comment]
its time to do some contribution from your side 
because i m so busy in my life or u can say im lazy

but in 2 month i will try new Api for this IF possible i left website pen testing 12 month ago

i m lazy to start back but u can provide solution for url or links i will add code

**Comment by profesionalleet1337** [comment]
> its time to do some contribution from your side because i m so busy in my life or u can say im lazy
> 
> but in 2 month i will try new Api for this IF possible i left website pen testing 12 month ago
> 
> i m lazy to start back but u can provide solution for url or links i will add code




Glad to hear from you again after half a year, didn't know you were going to join haha. I haven't used the tool in truth it quite a while, hopefully it works properly  in curent days, too ! 
-About the links and urls, when I wrote you I tested quite a few tools, none of which worked with that option to have url and link's in them , just need an free good API key maybe, I don't know.
Unfortunately, even if I have the desire, I have no knowledge of coding etc, meaning I have no way of helping you, although I would like to and I'm still looking for a free one that I can use to send some url's sms  from laptop to the number,  I'll keep an eye on things, hopefully there are developments no matter when you do it.

**Comment by security-softwares** [comment]
sure new tool working is started after that i will make SMS spoof tool i have to find or hack and api of website and manipulate the main message as api sends otp to user i will remove and change otp request to an SMS spoof request by manipulating otp  as main message that our tool user wants to send 


by the way whats ur name  u can contact me on telegram t.me/alien935

**Comment by security-softwares** [comment]
ok i will make new tool for this 
but name will be sms spoof not anonymous sms

**Comment by security-softwares** [comment]
ok i will make new tool names as sms spoof 
but not anonymous sms
because that will be advance one

**Comment by security-softwares** [comment]
new tool arrived for insta followers 
t.me/nirvan_marg

i changed username
